# Generated by Django 4.2.3 on 2024-02-25 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_word', models.IntegerField(default=0, help_text='عدد صحیح با مقدار حداقل 0 و حداکثر 5000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('typ_content', models.CharField(choices=[('landing', 'لندینگ'), ('product_description', 'توضیح محصول'), ('article', 'مقاله'), ('reportage', 'رپورتاژ')], default='landing', help_text='یکی از گزینه\u200cهای لندینگ، توضیح محصول، مقاله یا رپورتاژ را انتخاب کنید.', max_length=50)),
                ('level_content', models.CharField(choices=[('simple_content', 'ساده'), ('Semi-specialized_content', 'محتوا نیمه تخصصی'), ('Specialized_content', 'محتوای تخصصی')], default='simple_content', help_text='یکی از گزینه\u200cهای ساده، محتوا نیمه تخصصی، محتوا تخصصی را انتخاب کنید.', max_length=50)),
                ('title', models.CharField(max_length=180)),
                ('keyword', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, default='defalt.jpg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_uploade_file', models.FileField(upload_to='orders/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
