# Generated by Django 4.2.3 on 2023-09-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='keyword',
            field=models.CharField(max_length=180),
        ),
    ]
