# Generated by Django 4.2.3 on 2023-11-21 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='level_content',
            field=models.CharField(choices=[('simple_content', 'ساده'), ('Semi-specialized content', 'محتوا نیمه تخصصی'), ('Specialized content', 'محتوای تخصصی')], default='simple_content', help_text='یکی از گزینه\u200cهای ساده، محتوا نیمه تخصصی، محتوا تخصصی را انتخاب کنید.', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='num_word',
            field=models.IntegerField(default=None, help_text='عدد صحیح با مقدار حداقل 0 و حداکثر 5000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='order',
            name='typ_content',
            field=models.CharField(choices=[('landing', 'لندینگ'), ('product_description', 'توضیح محصول'), ('article', 'مقاله'), ('reportage', 'رپورتاژ')], default='landing', help_text='یکی از گزینه\u200cهای لندینگ، توضیح محصول، مقاله یا رپورتاژ را انتخاب کنید.', max_length=50),
        ),
    ]
